
# API -------------------------------------
server.port: ${PORT}

# LOGGING ---------------------------------
logging.level.root: ${LOG_LEVEL}

# DATABASE ---------------------------------
spring:
  h2:
    console:
      enabled: false
  datasource:
    url: jdbc:h2:file:/h2/kotlin-app-db
    username: sa
    password: ""
    driverClassName: org.h2.Driver
  jpa:
    hibernate.ddl-auto: update
    show-sql: false